### ISSUE TITLE
Sending failed when sharing content through whatsapp

### ISSUE THREAD

**Issue by ylin1CoR** [richmondrcmp/mobileapp#29] opened 2019-04-05 20:53 UTC
**Describe the bug**
Issue: When sharing content through whatsapp, it sometimes fail

**To Reproduce**
1. Go to Calendar of evens
2. Click on Public Works Open House event
3. Click the share link, and share content via Whatsapp
4. Click send on whatsapp, and an error displays 
5. Repeat step 4, and error still displays

**Expected behavior**
Should be able to send.

**Screenshots**
Will send over video

**Smartphone (please complete the following information):**
iphone 7 ios12.2

**Additional context**
Note: I did notice that the user's connection switched back to wifi at this point (instead of using LTE)

**Comment by rcmp-randallw** [comment] 2019-04-05 23:14
Here are some videos that outline the issue:
https://1drv.ms/v/s!Au0wmqpYyP_CiYw_uRJZX7sPpYK4-g
https://1drv.ms/v/s!Au0wmqpYyP_CiYw-p-VcicJyejTkQQ

and the top bar colouring makes it difficult see the Cancel and Send buttons:
![20190405_224508000_iOS](https://user-images.githubusercontent.com/47233113/55660945-c3fbb800-57bd-11e9-9623-9af733be619d.jpg)
![20190405_224543000_iOS](https://user-images.githubusercontent.com/47233113/55660946-c3fbb800-57bd-11e9-8c4d-4f0d54851922.jpg)
![20190405_224554000_iOS](https://user-images.githubusercontent.com/47233113/55660947-c3fbb800-57bd-11e9-95b9-70d228654204.jpg)

**Comment by rcmp-randallw** [comment] 2019-04-10 05:18
When you try to share a page via WhatsApp the cancel button (allowing you to return) is hard to see because it is white on grey, similar to the Send button above:
![20190404_020428000_iOS](https://user-images.githubusercontent.com/16924236/55529469-7153bc00-5656-11e9-9c69-d918a25f32d3.png)

but it appears if we share a Safari page via WhatsApp:
![20190404_020413000_iOS](https://user-images.githubusercontent.com/16924236/55529491-86c8e600-5656-11e9-8b59-e33db514c15d.png)

**Comment by jcarterOCV** [comment] 2019-04-11 06:42
Will be updated in build 18

**Comment by rcmp-randallw** [comment] 2019-04-13 13:46
Confirmed the Cancel and Send buttons now appear when sharing content via WhatsApp.

**Comment by jcarterOCV** [comment] 2019-05-20 21:14
This should be closed as this issue was resolved in a previous build.

**Closed** 2019-05-20 23:43 UTC
Labels: Issue Type - Bug, Priority - High
